name: ci

on:
  push:
    branches-ignore: ["ci"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn dev:build
      - if: contains(github.ref, 'main')
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git add -f dist docs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "$MESSAGE"
          git push origin main:ci -f